### ISSUE TITLE
Permission for full control over private repositories necessary?

### ISSUE THREAD

**Issue by taylorthurlow** [Daskiworks/ghwatch#118]
OAuth permissions through GitHub require full private repository access. Do notifications for private repositories not fall under the "access notifications" permission? I'm basically curious as to why the application needs access to private repositories.

![Screen Shot 2019-03-18 at 3 51 25 PM](https://user-images.githubusercontent.com/761640/54568769-bb217e80-4995-11e9-9867-08a2b843ab1b.png)

**Comment by velias** [comment]
Hi @taylorthurlow,

app currently asks for scopes [`notifications` and `repo`](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes) during authentication.

`repo` scope had been introduced in #37 because github.com notification API (covered by the `notification` scope) does not provide enough detailed information, eg. it even doesn't provide view URL. So app have to perform subsequent calls to other APIs to obtain details related to the notification and it requires this higher permissions for private repositories. Later I added more info showing into the app obtained through this additional call. 

Unfortunately GitHub doesn't provide any "readonly" privilege to access information from private repositories, only this full control. I'm not fully happy about it also, readonly should be enough.

I also asked GitHub to add more info into notification API response directly to prevent these additional API calls at all, but they refused to do it.

**Comment by taylorthurlow** [comment]
Understood. Thanks for getting back to me!
