### ISSUE TITLE
Log in via browser

### ISSUE THREAD

**Issue by GerkinDev** [Daskiworks/ghwatch#122]
Hi,

I'd be glad to install this app, but I won't type my credentials in a 3rd party app. Why don't you use bearer tokens after an in-browser login? What are the limitations?

Cheers

**Comment by GerkinDev** [comment]
Hi,

Could you please inform me about this question ? This is a potential security issue, so your explanation would reassure me.

Thank you in advance.

**Comment by velias** [comment]
Hi, sorry for late reply in bussy Christmas time. I didn't use in-browser login as I was not able to find any example/guide how to do it correctly and securely, and I really didn't want to bring any security risc due to wong integration. So I implemented it in a way which is fully under my control. 
In my implementation, password is never stored in the app, it is only sent to github API to acquire token, which is stored and used for subsequent API calls (you can see it in your Github profile).
If you know about any guide how to do use in-browser login let me know, I can change app if I'll be sure how to do it correctly.

**Comment by GerkinDev** [comment]
Hi

I've recently installed an application that allows login through browser. Here is the [login class](https://github.com/ThirtyDegreesRay/OpenHub/blob/master/app/src/main/java/com/thirtydegreesray/openhub/mvp/presenter/LoginPresenter.java), maybe you can find resources you are looking for. Unfortunatelly, I could not find the view & understand what method is called when login is done through the browser.

**Comment by velias** [comment]
I got an email from github that Authentication REST API will be disabled during autumn 2020. So app have to be updated to use browser flow.

**Comment by velias** [comment]
Change is implemented, it uses Android AccountManager so account is visible in common Android Account settings
