### ISSUE TITLE
Add warn dialogs when user sets some option which may cause higher data consumption

### ISSUE THREAD

**Issue by velias** [Daskiworks/ghwatch#95]
Add warn dialogs with explanation when user sets some app settings option which may cause higher data consumption. Affected options:
* "New notifications check period" set to value lower than 60 minutes
* "Check over WiFi only" disabled
* "Better read detection" enabled
* "Load notification detail" enabled
* "Show Labels" enabled

Dialogs should be shown only once per option when user is on Setting screen and changes the option back and forth. Should be shown again later.

**Comment by laughedelic** [comment]
I'm just curious, where does this concern about data consumption come from? I saw several open issues here about it and before that I was genuinely surprised when I saw "a bit higher resource consumption" warning on every setting. I thought "well, it's kind of obvious, but if it warns you, probably it really does something extra?", which means that these notes make more impression on the user than they should. 

> Dialogs should be shown only once per option when user is on Setting screen and changes the option back and forth. Should be shown again later.

Honestly, I think this is too much. Just from the UX point of view. Additional dialogs are annoying.

On one hand care about user's data consumption is good and **having granular settings for it is great**. But on another hand, if walk into a candy store to buy some candies, I don't want to be warned about sugar consumption every time I choose a candy: that's what I came for. I'm using this application dedicated to delivering Github notifications to **stay connected** (that's what notifications are about, right?), so I want to get notified and if I miss some important notification because of too restrictive default settings, I will be upset and think that this application hasn't delivered what it's made for.

**Comment by velias** [comment]
I have 1 star review from user who has very high consumpion. And it also happen to my friend, his monthly data plan was wasted by this app (he has about 3500 unread botifications ;-) So I'm trying to introduce some safety for these cases. It is not easy to balance.

**Comment by velias** [comment]
Maybe instead of this I should implement some mechanism which monitors data consumption by the app (not sure if android provides api to get this info) and warns user if it is too high during some time period.

**Comment by laughedelic** [comment]
> I have 1 star review from user who had very high consumpion. And it also happened to my friend, his monthly data plan was wasted by this app (he has about 3500 unread notifications ;-)

It sounds a bit suspicious for a notification app.. It shouldn't consume much. Probably it's requesting more data than it needs? Could you point me to the code where it fetches notifications?

**Comment by velias** [comment]
Problem is that github notifications REST API v3 is really bad. It sends lots of informations for each notification, most of them unusable. And some other info (like status of issue or PR related to the notification) is missing so separate request must be performed to obtain it.
One thing I want to investigste now is if this REST API supports gzip compression on wire and use this if yes

**Comment by velias** [comment]
Most code is in UnreadNotificationsService

**Comment by velias** [comment]
Github notifications api supports asking for new notifications only. I use this for background check, but I must do full load from time to time to remove notifications read on other devices, as they are not in difs

**Comment by laughedelic** [comment]
Yeah, I see. I just thought whether you actually do incremental queries or every time run full retrieval for some fixed period of time..

GraphQL API would solve the issue with the exact data you want to get, so it's a pity that it's not available for notifications/events.
